global:
  spring:
    dbUrl: "jdbc:postgresql://configuration-db:5432/"
    dbUsername: "postgres"
    dbPassword: "postgres"
    useDefaultConsul: false

infrastructure:
  genericServices:
    configuration-db:
      enabled: true
      storageClassName:	nfs-delete