global:
  spring:
    dbUrl: "jdbc:postgresql://configuration-db:5432/"
    dbUsername: "postgres"
    dbPassword: "postgres"
    useDefaultConsul: false

config:
  config-backend:
    resources:
      limits:
        memory: 512Mi
        cpu: 300m
    enabled: true
  config-web:
    resources:
      limits:
        memory: 512Mi
        cpu: 300m
    enabled: true

infrastructure:
  genericServices:
    configuration-db:
      enabled: true
      storageClassName:	nfs-delete