version: '3.6'

services:

  postgres:
    image: postgres:9.6.11-alpine
    ports:
      - 8962:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=configuration
    deploy:
      resources:
        limits:
          memory: 1024M
      placement:
        constraints:
          - node.labels.type == db

  config-service:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/configuration
      - JAVA_OPTS=-Xmx200m
      - SERVER_PORT=8080
      - SERVER_SERVLET_CONTEXT_PATH=/configs/service
    ports:
      - 8961:8080
    deploy:
      resources:
        limits:
          memory: 700M
      restart_policy:
        max_attempts: 3
      placement:
        constraints:
          - node.labels.dc == hetzner
    healthcheck:
      test: curl -f http://localhost:8080/configs/service/monitoring/health | grep -io '^{"status":"UP"' || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 300s

  config-web:
    environment:
      - CONFIG_BACKEND_URL=http://audit-service:8080/configs/service/api
      - JAVA_OPTS=-Xmx300m
      - SERVER_PORT=8080
      - SERVER_SERVLET_CONTEXT_PATH=/configs
    ports:
      - 8960:8080
    deploy:
      resources:
        limits:
          memory: 800M
      restart_policy:
        max_attempts: 3
      placement:
        constraints:
          - node.labels.dc == hetzner
    healthcheck:
      test: curl -f http://localhost:8080/configs/monitoring/health | grep -io '^{"status":"UP"' || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 300s