version: "3.6"

services:

  config-backend:
    build:
      context: config-backend
      args:
        JAR_FILE: target/config-backend.jar

  config-web:
    build:
      context: config-webapp
      args:
        JAR_FILE: target/config-webapp.jar
