version: "3.6"

services:

  config-service:
    build:
      context: config-service
      args:
        JAR_FILE: target/config-service.jar

  config-web:
    build:
      context: config-webapp
      args:
        JAR_FILE: target/config-webapp.jar
