databaseChangeLog:
  - changeSet:
      id: create_configuration_group
      author: ilebedenko
      dbms: postgresql
      changes:
        - sqlFile:
            path: db/sql/V2_configuration_group.sql