databaseChangeLog:
  - changeSet:
      id: create_configuration_system
      author: ilebedenko
      dbms: postgresql
      changes:
        - sqlFile:
            path: db/sql/V3_configuration_system.sql