databaseChangeLog:
  - changeSet:
      id: add_columns_to_application
      author: ilebedenko
      dbms: postgresql
      changes:
        - sqlFile:
            path: db/sql/V13_add_columns_to_application.sql