databaseChangeLog:
  - changeSet:
      id: change_application_constraint
      author: ilebedenko
      dbms: postgresql
      changes:
        - sqlFile:
            path: db/sql/V17_update_system_application_tables.sql