databaseChangeLog:
  - changeSet:
      id: create_config_group_code
      author: ilebedenko
      dbms: postgresql
      changes:
        - sqlFile:
            path: db/sql/V4_config_group_code.sql